static_friction_gain: 0.1
viscous_friction_gain: 0.2
global_friction_gain: 0.95
inertia_compensation_gain: 1.0
torque_derivative_feedback_gain: 0.0
velocity_friction_compensation_tolerance: 1e-2
feed_forward_acceleration_gain: 1.0

ripple_phase_offset: 0.0
ripple_amplitude: 0.0
ripple_compensation_gain: 0.0

acceleration_differentiator:
  initial_value: 0.
  order: 5

  differentiator_type: OneSide
  differentiator_order: FirstOrder

acceleration_filter_type: ButterworthFilterd
acceleration_filter:
  filter_parameters:
    - order: 5
      type: LowPass
      composition_type: Sequence
      cutoff1: 500.0
      cutoff2: 0.0

torque_sensor_filter_type: ButterworthFilterd
torque_sensor_filter:
  filter_parameters:
    - order: 5
      type: LowPass
      composition_type: Sequence
      cutoff1: 500.0
      cutoff2: 0.0

command_filter_type: ButterworthFilterd
command_filter:
  filter_parameters:
    - order: 5
      type: LowPass
      composition_type: Sequence
      cutoff1: 500.0
      cutoff2: 0.0
    - order: 5
      type: LowPass
      composition_type: Sequence
      freq: 1000.0
      cutoff1: 500.0
      cutoff2: 0.0

use_filtered_torque_sensor: false
use_filtered_acceleration: false
use_filtered_command: false
