ball_screw_efficiency: 0.0
ball_screw_lead: 0.0
motor_torque_constant: 0.1031
torque_sensor_offset: 0.0
reduction_ratio: 100
actuator_names:
  - pendulum_motor
check_mode: false
dt: 0.001

# This parametres are random, they have not been identified
motor_inertia: 0.000191658
static_friction: 0.1
viscous_friction: 0.3
joint_elasticity: 10000.0
joint_elasticity_damping: -20.
